hyperparameters:
  model_arch: mobile_vit
  total_epochs: 500
  batch_size: 128

  optimizer:
    type: adamw
    lr: 0.002
    beta_1: 0.9
    beta_2: 0.999
    scheduler: cosine_annealing
    weight_decay: 0.05
    smoothing: 0.1

data:
  dataset: svhn
  num_classes: 10
  num_channels: 3
  input_size: 224 
  num_workers: 16

  augment:
    horizontal_flip: 0.5
    randaug_n: 2
    resize_scale: [0.08, 1.0]
    resize_ratio: [0.75, 1.3333]
    reprob: 0.25
    remode: pixel
    recount: 1
    autoaugment: True
