hyperparameters:
  model_arch: deit
  total_epochs: 500
  batch_size: 128
  
  vit:
    patch_size: 4
    emb_dim: 192
    depth: 12
    heads: 3
    mlp_ratio: 4.0
    proj_drop: 0.1
    attn_drop: 0.1

  distillation:
    temperature: 3.0
    alpha: 0.5
    hard: False  # use soft distillation (kldiv)

  optimizer:
    type: adamw
    lr: 0.001
    beta_1: 0.9
    beta_2: 0.999
    scheduler: cosine_annealing
    weight_decay: 0.05

data:
  dataset: svhn
  num_classes: 10
  num_channels: 3
  input_size: 32
  num_workers: 16

  augment:
    horizontal_flip: 0.5
    randaug_n: 2
    resize_scale: [0.08, 1.0]
    resize_ratio: [0.75, 1.3333]
    reprob: 0.25
    remode: pixel
    recount: 1
    autoaugment: True
